backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

display_url: https://oriolcastro.me

logo_url: https://res.cloudinary.com/okstudio/image/upload/v1552298710/me.jpg

collections:
  - name: "blog_ca"
    label: "Blog - CA"
    folder: "src/pages/blog/ca"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Locale", name: "locale", widget: "hidden", default:  "ca"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "blog_en"
    label: "Blog - EN"
    folder: "src/pages/blog/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Locale", name: "locale", widget: "hidden", default:  "en"}
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "single-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
    # files:
    #   - file: "src/pages/about/index.md"
    #     label: "About"
    #     name: "about"
    #     fields:
    #     - {
    #           label: "Template Key",
    #           name: "templateKey",
    #           widget: "hidden",
    #           default: "portfolio-page",
    #         }
    #       - { label: "Title", name: "title", widget: "string" }
    #       - { label: "Featured Image", name: "thumbnail", widget: "image" }
    #       - { label: "Body", name: "body", widget: "markdown" }
